# Codecov Configuration for testcontainers-swift
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

# Ignore paths that shouldn't be included in coverage
ignore:
  - ".build/**/*"
  - "Tests/**/*"
  - "Examples/**/*"
  - "**/*.generated.swift"
  - "**/Mocks/**/*"

# Flag management for different test types
flags:
  unittests:
    paths:
      - Sources/
    carryforward: true
  swift:
    paths:
      - Sources/Testcontainers/
    carryforward: true
  linux:
    paths:
      - Sources/
    carryforward: true

# Comment configuration for PRs
comment:
  layout: "header,diff,flags,components,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# GitHub Checks integration
github_checks:
  annotations: true
